INSERT INTO `Parks` VALUES (null, "Joshua Tree National Park", "Two distinct desert ecosystems, the Mojave and the Colorado, come together in Joshua Tree National Park. A fascinating variety of plants and animals make their homes in a land sculpted by strong winds and occasional torrents of rain. Dark night skies, a rich cultural history, and surreal geologic features add to the wonder of this vast wilderness in southern California.", "Twentynine Palms", "California", 34.070442,-116.060294);
INSERT INTO `Parks` VALUES (null, "Everglades National Park", "Everglades National Park protects an unparalleled landscape that provides important habitat for numerous rare and endangered species like the manatee,  American crocodile, and the elusive Florida panther. An international treasure as well -  a World Heritage Site, International Biosphere Reserve, a Wetland of International Importance, and a specially protected area under the Cartagena Treaty.", "Homestead", "Florida", 25.7459, 80.5550 );
INSERT INTO `Parks` VALUES (null, "Great Smoky Mountains National Park", "Ridge upon ridge of forest straddles the border between North Carolina and Tennessee in Great Smoky Mountains National Park. World renowned for its diversity of plant and animal life, the beauty of its ancient mountains, and the quality of its remnants of Southern Appalachian mountain culture, this is America's most visited national park.", "Gatlinburg", "Tennessee", 35.672619, -83.512053);
INSERT INTO `Parks` VALUES (null, "Haleakalā National Park", "This special place vibrates with stories of ancient and modern Hawaiian culture and protects the bond between the land and its people. The park also cares for endangered species, some of which exist nowhere else. Come visit this special place - renew your spirit amid stark volcanic landscapes and sub-tropical rain forest with an unforgettable hike through the backcountry.", "Makawao", "Hawaii", 20.7204, -156.1552);
INSERT INTO `Parks` VALUES (null, "Yosemite National Park", "Not just a great valley, but a shrine to human foresight, the strength of granite, the power of glaciers, the persistence of life, and the tranquility of the High Sierra. First protected in 1864, Yosemite National Park is best known for its waterfalls, but within its nearly 1,200 square miles, you can find deep valleys, grand meadows, ancient giant sequoias, a vast wilderness area, and much more.", "Sierra Nevada", "California", 37.8651, 119.5383);
INSERT INTO `Parks` VALUES (null, "Glacier National Park", "A showcase of melting glaciers, alpine meadows, carved valleys, and spectacular lakes. With over 700 miles of trails, Glacier is a paradise for adventurous visitors seeking wilderness steeped in human history. Relive the days of old through historic chalets, lodges, and the famous Going-to-the-Sun Road.", "Northwest Montana", "Montana", 48.7596, 113.7870);
INSERT INTO `Parks` VALUES (null, "Kenai Fjords National Park", "At the edge of the Kenai Peninsula lies a land where the ice age lingers. Nearly 40 glaciers flow from the Harding Icefield, Kenai Fjords' crowning feature. Wildlife thrives in icy waters and lush forests around this vast expanse of ice. Sugpiaq people relied on these resources to nurture a life entwined with the sea. Today, shrinking glaciers bear witness to the effects of our changing climate.", "Seward", "Alaska", 59.8487, -149.8163);
INSERT INTO `Parks` VALUES (null, "Shenandoah National Park", "Shenandoah National Park is a land bursting with cascading waterfalls, spectacular vistas, fields of wildflowers, and quiet wooded hollows. With over 200,000 acres of protected lands that are haven to deer, songbirds, and black bear, there's so much to explore.", "Jollett", "Virginia", 38.4755, -78.4535);
INSERT INTO `Parks` VALUES (null, "Saguaro National Park", "Tucson, Arizona is home to the nation's largest cacti. The giant saguaro is the universal symbol of the American west. These majestic plants, found only in a small portion of the United States, are protected by Saguaro National Park, to the east and west of the modern city of Tucson. Here you have a chance to see these enormous cacti, silhouetted by the beauty of a magnificent desert sunset.", "Tuscon", "Arizona", 32.2967, 111.1666);

INSERT INTO `Natural_Attractions` VALUES (null, "Cascading waterfalls");
INSERT INTO `Natural_Attractions` VALUES (null, "Hiking");
INSERT INTO `Natural_Attractions` VALUES (null, "Backpacking");
INSERT INTO `Natural_Attractions` VALUES (null, "Appalachian trail");
INSERT INTO `Natural_Attractions` VALUES (null, "Rock climbing");
INSERT INTO `Natural_Attractions` VALUES (null, "Rock formations");
INSERT INTO `Natural_Attractions` VALUES (null, "Camping");
INSERT INTO `Natural_Attractions` VALUES (null, "Rivers");
INSERT INTO `Natural_Attractions` VALUES (null, "Creeks");
INSERT INTO `Natural_Attractions` VALUES (null, "Forest");
INSERT INTO `Natural_Attractions` VALUES (null, "Desert");
INSERT INTO `Natural_Attractions` VALUES (null, "Wildlife");
INSERT INTO `Natural_Attractions` VALUES (null, "Wildflowers");
INSERT INTO `Natural_Attractions` VALUES (null, "Biological diversity");
INSERT INTO `Natural_Attractions` VALUES (null, "Cacti");
INSERT INTO `Natural_Attractions` VALUES (null, "Glaciers");
INSERT INTO `Natural_Attractions` VALUES (null, "Wetland");
INSERT INTO `Natural_Attractions` VALUES (null, "Mangrove ecosystem");
INSERT INTO `Natural_Attractions` VALUES (null, "Marine ecosystems");
INSERT INTO `Natural_Attractions` VALUES (null, "Scenic drives");
INSERT INTO `Natural_Attractions` VALUES (null, "Native American history");
INSERT INTO `Natural_Attractions` VALUES (null, "Bird watching");
INSERT INTO `Natural_Attractions` VALUES (null, "Winds");
INSERT INTO `Natural_Attractions` VALUES (null, "Scenic drives");
INSERT INTO `Natural_Attractions` VALUES (null, "Deities in the parks");
INSERT INTO `Natural_Attractions` VALUES (null, "Spectacular vistas");
INSERT INTO `Natural_Attractions` VALUES (null, "Giant trees");
INSERT INTO `Natural_Attractions` VALUES (null, "Deep valleys");
INSERT INTO `Natural_Attractions` VALUES (null, "Alpine meadows");

INSERT INTO `Campgrounds` VALUES (null, "Upper Pines", 5, 37, "Upper Pines is located near the Merced River in Yosemite Valley. Yosemite Valley is centrally located in the park and boasts some of Yosemite’s most iconic features. This large campground is located at 4,000 feet (1,219 m) elevation and can be accessed from all park roads. Upper Pines is within biking and walking distance of many services and trailheads in Yosemite Valley and is located on the free shuttle route. There are food and grocery services nearby at Curry Village and Yosemite Village.");
INSERT INTO `Campgrounds` VALUES (null, "Yosemite Creek", 5, 75, "Yosemite Creek Campground is located nearly 5 miles off the Tioga Road (via a rough road) 26 miles west of Tuolumne Meadows, and a little over an hour from Yosemite Valley. Located in the forest at 7,700 feet (2,300 m) many campsites are close to Yosemite Creek, which is the only water source (must be filtered, treated, or boiled). RVs and Trailers are not recommended for this harder to access, and more primitive campground. There are no visitor services close to the campground.");
INSERT INTO `Campgrounds` VALUES (null, "Black Rock", 1, 99, "This large (99 site) campground is located in the northwest corner of the park. Each campsite has a picnic table and fire ring with rest rooms and water nearby. Shopping facilities are only five miles away in the town of Yucca Valley. Campsites vary in size and can accommodate both tents and RVs. A day-use picnic area and a dump station are also available. For horse owners, a separate area is provided for camping or for staging a ride.");
INSERT INTO `Campgrounds` VALUES (null, "Indian Cove", 1, 101, "Indian Cove Campground is located off of Highway 62, thirteen miles east of Joshua Tree Village and ten miles west of Twentynine Palms on the north side of the Wonderland of Rocks. Indian Cove Road dead-ends at this secluded area. Indian Cove has 101 campsites, including thirteen group campsites. Between Memorial Day and Labor Day it is 39 reservable sites. There are vault toilets but no water at the campsites. Water is available at the small ranger station roughly two miles north of the campground.");
INSERT INTO `Campgrounds` VALUES (null, "Long Pine Key", 2, 45, "Only a few miles from the Ernest F. Coe Visitor Center, adjacent to the Long Pine Key Trail and encompassing a pleasant fishing pond, the Long Pine Key Campground provides all the essentials required for getting yourself in tune with nature.");
INSERT INTO `Campgrounds` VALUES (null, "Flamingo", 2, 15, "The campgrounds at Flamingo offer an unforgettable year-round experience in Everglades National Park.  There are plenty of pedestrian and bike trails and tons of wildlife.");
INSERT INTO `Campgrounds` VALUES (null, "Cataloochee", 3, 10, "Elevation 2,600 feet (792m) - located in historic Cataloochee Valley, is surrounded by mountain ranges and pristine streams characterized by mild winters and hot, humid summers. It offers traditional camping with the convenience of flush toilets and drinking water. There are no hookups or showers. Hammocks are allowed over the footprint of the campsite. Limited to trees 10 inches in diameter with adequate padding around the tree and only 2 hammocks may be suspended from tree.");
INSERT INTO `Campgrounds` VALUES (null, "Elkmont", 3, 23, "Elkmont Campground - elevation 2,150 feet (655m) - is the closest frontcountry camping area to Sugarlands Visitor Center in the North District of the park. The climate is characterized by mild winters and hot, humid summers. Mountain ranges and a pristine river are the backdrop for your Elkmont adventure. Elkmont Campground offers camping for both tents and RVs, with 220 sites total.");
INSERT INTO `Campgrounds` VALUES (null, "Hosmer Grove", 4, 6, "Hosmer Grove lies in the cloud belt of Haleakalā, at nearly 7,000 feet (2134m) in elevation in the Summit District. Come prepared for rain and cold weather! The forest comes to life in the early dawn with the many native birds in the area, making this a beautiful early morning hike.");
INSERT INTO `Campgrounds` VALUES (null, "Kīpahulu", 4, 20, "The Kīpahulu campground is about 1/8 mile (.2 km) south of the Kīpahulu Visitor Center. Sites overlook ocean cliffs and are a short walk from ʻOheʻo Gulch. Entry into the stream at any point in the park is prohibited. Be prepared for rain, harsh sun, and mosquitoes. There is no beach access.");
INSERT INTO `Campgrounds` VALUES (null, "Apgar", 6, 13, "Apgar campground is the largest campground in the park. It is situated in trees and provides tent and RV campers with shade and some privacy. Evening sunsets on Lake McDonald are only a short stroll, and you won't want to miss evening programs with a ranger at the Apgar Amphitheater. Many trails are located within a short drive of the campground. Five Group Sites are reservable in advance.");
INSERT INTO `Campgrounds` VALUES (null, "St Mary", 6, 32, "St. Mary Campground is the largest campground on the east side of Glacier National Park, and is conveniently located approximately a half-mile from the St. Mary Visitor Center. The visitor center offers interpretive programs, shuttle service and Red Bus tours leaving from the center. The campground sits near the entrance of the popular scenic byway, the Going-to-the-Sun Road.");
INSERT INTO `Campgrounds` VALUES (null, "Exit Glacier", 7, 10, "Exit Glacier is the primary destination for visitors to witness up close the power of the glaciers. It is also the home to the Exit Glacier Nature Center and the trail head for the Harding Icefield Trail.");
INSERT INTO `Campgrounds` VALUES (null, "Big Meadows", 8, 51, "Big Meadows Campground (mile 51.2) is centrally-located in Shenandoah National Park, providing easy access to many of the most popular destinations in the Park, including Big Meadows, Dark Hollow Falls, and Byrd Visitor Center. All sites include a place for a tent or RV, a fire ring, and a picnic table.");
INSERT INTO `Campgrounds` VALUES (null, "Lewis Mountain", 8, 26, "Lewis Mountain (mile 57.5), the smallest campground in Shenandoah National Park, appeals to those who want a little more privacy while still staying within a close distance to many of the most popular destinations in the Park, including Big Meadows (7 miles away).");
INSERT INTO `Campgrounds` VALUES (null, "Juniper Basin", 9, 3, "This campground is a strong day hike up the Tanque Verde Ridge over 6.9 miles and 3,000 feet of gain. Exceptional views can be seen throughout the hike, and habitats change quickly from desert scrub to oak savanna and pine/ juniper woodlands. Water here is very seasonal, and often dry during the spring and fall. Fires are allowed here, only from collecting dead and downed wood.");

INSERT INTO `Campgrounds` VALUES (null, "Grass Shack", 9, 11, "Grass Shack is a great campground that offers shade from large sycamores as well as other riparian species. Two of the larger streams-Chimenea Creek and Madrona Creek run through and by the campground, providing water most of the year. Fires are not allowed here being in a fragile riparian ecosystem surrounded by a thick grassland. Access is from Camino Loma Alta, and this ten mile hike climbs 2,200 feet to a campground often not affected by winter storms. Views are exceptional to the south as you climb through and above the saguaros. This is the first of two campgrounds on the Arizona Trail.");
INSERT INTO `Users` VALUES (null, "Frodo", "Baggins", "frodo@baggins.com","gandalfsucks12");
INSERT INTO `Users` VALUES (null, "Bilbo", "Baggins", "bilbo@baggins.com","gandalfsucks12");
INSERT INTO `Users` VALUES (null, "Thorin", "Oakenshield", "thorin@oakenshield.com","gandalfsucks12");
INSERT INTO `Users` VALUES (null, "Aragorn", "Elessar", "aragorn@elessar.com","gandalfsucks12");
INSERT INTO `Users` VALUES (null, "Samwise", "Gamgee", "samwise@gamgee.com","gandalfsucks12");
INSERT INTO `Users` VALUES (null, "Peregrin", "Took", "peregrin@took.com","gandalfsucks12");
INSERT INTO `Users` VALUES (null, "Meriadoc", "Brandybuck", "meriadoc@brandybuck.com","gandalfsucks12");
INSERT INTO `Users` VALUES (null, "Gandalf", "The Grey", "gandalf@thegrey.com","gandalfsucks12");
INSERT INTO `Users` VALUES (null, "Lady", "Galadriel", "lady@galadriel.com","gandalfsucks12");
INSERT INTO `Users` VALUES (null, "Lord", "Elrond", "lord@elrond.com","gandalfsucks12");

INSERT INTO `Favorite_Types` VALUES (null, "Blog");
INSERT INTO `Favorite_Types` VALUES (null, "Park");
INSERT INTO `Favorite_Types` VALUES (null, "Photo");
INSERT INTO `Favorite_Types` VALUES (null, "Event");

INSERT INTO Amenities VALUES (null, 'Parking');
INSERT INTO Amenities VALUES (null, 'Restrooms');
INSERT INTO Amenities VALUES (null, 'Dining');
INSERT INTO Amenities VALUES (null, 'Camping');

INSERT INTO Park_Amenities VALUES (null, null, 2, 1);
INSERT INTO Park_Amenities VALUES (null, null, 2, 2);
INSERT INTO Park_Amenities VALUES (null, null, 2, 3);
INSERT INTO Park_Amenities VALUES (null, null, 2, 4);
INSERT INTO Park_Amenities VALUES (null, null, 2, 5);
INSERT INTO Park_Amenities VALUES (null, null, 2, 7);
INSERT INTO Park_Amenities VALUES (null, null, 2, 8);
INSERT INTO Park_Amenities VALUES (null, null, 2, 9);

INSERT INTO Park_Amenities VALUES (null, null, 1, 1);
INSERT INTO Park_Amenities VALUES (null, null, 1, 2);
INSERT INTO Park_Amenities VALUES (null, null, 1, 3);
INSERT INTO Park_Amenities VALUES (null, null, 1, 4);
INSERT INTO Park_Amenities VALUES (null, null, 1, 5);
INSERT INTO Park_Amenities VALUES (null, null, 1, 6);
INSERT INTO Park_Amenities VALUES (null, null, 1, 7);
INSERT INTO Park_Amenities VALUES (null, null, 1, 8);
INSERT INTO Park_Amenities VALUES (null, null, 1, 9);

INSERT INTO Park_Amenities VALUES (null, 'Gator Grub', 3, 2);
INSERT INTO Park_Amenities VALUES (null, 'Old Smoky Links', 3, 3);
INSERT INTO Park_Amenities VALUES (null, 'Family Restaurant', 3, 1);
INSERT INTO Park_Amenities VALUES (null, 'The Birdfeeder', 3, 8);
INSERT INTO Park_Amenities VALUES (null, 'Prickles', 3, 9);

INSERT INTO `Wildlife_Groups` VALUES (null, "Mammals");
INSERT INTO `Wildlife_Groups` VALUES (null, "Reptiles");
INSERT INTO `Wildlife_Groups` VALUES (null, "Amphibians");
INSERT INTO `Wildlife_Groups` VALUES (null, "Fish");

INSERT INTO Events VALUES (null, "Yoga Retreat in Joshua Tree", "Are you ready to connect with Self, others, nature, community and experience a private sound bath at the Integratron?", '2023-05-26 15:00:00', 1);
INSERT INTO Events VALUES (null, "Leafy, Barky, Toxic?", "The Everglades are home to a variety of tropical plants. Explore local plant life and fun facts. Program travels about ¼ mile (.25 km). Meet in front of the visitor center. 30 minutes.", '2023-04-22 08:30:00', 2);
INSERT INTO Events VALUES (null, "Ponies in the Smokies", "Come and enjoy the beautiful Smoky Mountains and kick off the car show season right at Ponies in the Smokies! There are indoor vendors, competitions, and shows you don't want to miss at this popular car show.", '2023-03-20 18:00:00', 3);
INSERT INTO Events VALUES (null, "Hosmer Hike", "Join a ranger for a free guided walk through Hosmer Grove. Listen to endemic forest birds, identify native Hawaiian plants, and learn a little more about the past, present, and future of this unique place.  Participation is first-come, first-served.", '2023-01-28 10:00:00', 4);
INSERT INTO Events VALUES (null, "Bigfoot Hunting", "As the legends go, there is a being of great intellect and strength trolling the woods of Yosemite National Park - or is there? Join us on our 3-day, 2-night expedition into the unknown to find out.", '2023-03-24 07:15:00', 5);
INSERT INTO Events VALUES (null, "Glacier Photo Workshop", "Glacier National Park is a landscape photographer’s paradise. Join us for a fall photo workshop in an unforgettable setting.", '2023-09-19 16:00:00', 6);
INSERT INTO Events VALUES (null, "Ice Fishing in the Kenai Fjords", "The fjords and Resurrection Bay are hotspots for salmon, halibut, rockfish, and lingcod. Many anglers even fish right from shore in and around Seward. State fishing licenses are required for all area fishing.", '2023-06-24 04:15:00', 7);
INSERT INTO Events VALUES (null, "Rapidan Camp Tours", "Rapidan Camp is the former summer retreat of President Herbert and First Lady Lou Henry Hoover. On this tour, a ranger guides you on a hike through this historic landmark.", '2023-02-14 11:30:00', 8);
INSERT INTO Events VALUES (null, "Investigation of the 1000 Year Old Rock Art!", "Become a Rock Art Detective and investigate the who, when, and how mysteries of the 1000 year old Hohokam Petroglyphs. An optional 1/4 mile hike will follow the program, discussing some of the common plants and animals found here in the desert.", '2023-10-24 11:15:00', 9);

INSERT INTO Event_Registration VALUES (null, 1, 9);
INSERT INTO Event_Registration VALUES (null, 1, 8);
INSERT INTO Event_Registration VALUES (null, 2, 10);
INSERT INTO Event_Registration VALUES (null, 2, 9);
INSERT INTO Event_Registration VALUES (null, 3, 4);
INSERT INTO Event_Registration VALUES (null, 3, 3);
INSERT INTO Event_Registration VALUES (null, 4, 2);
INSERT INTO Event_Registration VALUES (null, 4, 3);
INSERT INTO Event_Registration VALUES (null, 5, 1);
INSERT INTO Event_Registration VALUES (null, 5, 6);
INSERT INTO Event_Registration VALUES (null, 5, 7);
INSERT INTO Event_Registration VALUES (null, 5, 5);
INSERT INTO Event_Registration VALUES (null, 6, 5);
INSERT INTO Event_Registration VALUES (null, 6, 1);
INSERT INTO Event_Registration VALUES (null, 7, 9);
INSERT INTO Event_Registration VALUES (null, 7, 10);
INSERT INTO Event_Registration VALUES (null, 8, 8);
INSERT INTO Event_Registration VALUES (null, 8, 2);
INSERT INTO Event_Registration VALUES (null, 9, 6);
INSERT INTO Event_Registration VALUES (null, 9, 7);

ALTER TABLE `users`
ADD COLUMN `isRanger` boolean; 

UPDATE `users`
SET isRanger = false
WHERE id <= 10;

INSERT INTO `Users` VALUES (null, "Smoky", "Bear", "smokybear@nationalparks.com","bearyhappy", true);

INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232167/National-Parks/Park-Photos/joshua_tree_2_np863y.jpg", 11, 1);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232168/National-Parks/Park-Photos/joshua_tree_4_p1hwpc.jpg", 11, 1);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232168/National-Parks/Park-Photos/joshua_tree_1_my5yzw.jpg", 11, 1);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232169/National-Parks/Park-Photos/joshua_tree_3_xeuael.jpg", 11, 1);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232176/National-Parks/Park-Photos/everglades_3_jctxp5.jpg", 11, 2);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232177/National-Parks/Park-Photos/everglades_4_arkanp.jpg", 11, 2);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232177/National-Parks/Park-Photos/everglades_1_otti4j.jpg", 11, 2);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232178/National-Parks/Park-Photos/everglades_2_hkp3sw.jpg", 11, 2);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232184/National-Parks/Park-Photos/great_smoky_3_vojzn3.jpg", 11, 3);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232185/National-Parks/Park-Photos/great_smoky_1_hv505f.jpg", 11, 3);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232187/National-Parks/Park-Photos/great_smoky_2_opfzby.jpg", 11, 3);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232194/National-Parks/Park-Photos/Haleakala%CC%84_2_ggoljm.jpg", 11, 4);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232194/National-Parks/Park-Photos/Haleakala%CC%84_3_opcuyb.jpg", 11, 4);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232195/National-Parks/Park-Photos/Haleakala%CC%84_1_bidyin.jpg", 11, 4);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232205/National-Parks/Park-Photos/Yosmite_5_whh42c.jpg", 11, 5);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232207/National-Parks/Park-Photos/Yosemite_1_hfz28r.jpg", 11, 5);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232207/National-Parks/Park-Photos/Yosemite_4_agiwe5.jpg", 11, 5);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232207/National-Parks/Park-Photos/Yosemite_2_vuanbz.jpg", 11, 5);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232208/National-Parks/Park-Photos/Yosemite_3_xekp2k.jpg", 11, 5);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232217/National-Parks/Park-Photos/glacier_3_whygqo.jpg", 11, 6);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232217/National-Parks/Park-Photos/glacier_1_ihkmyw.jpg", 11, 6);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232218/National-Parks/Park-Photos/glacier_2_tqjhue.jpg", 11, 6);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232228/National-Parks/Park-Photos/kenai_3_u3za9b.jpg", 11, 7);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232228/National-Parks/Park-Photos/kenai_1_gcexww.jpg", 11, 7);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232229/National-Parks/Park-Photos/kenai_2_bdhbj1.jpg", 11, 7);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232229/National-Parks/Park-Photos/kenai_4_bldbur.jpg", 11, 7);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232236/National-Parks/Park-Photos/shenandoah_3_dvtung.jpg", 11, 8);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232236/National-Parks/Park-Photos/shenandoah_2_bpn61w.jpg", 11, 8);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232237/National-Parks/Park-Photos/shenandoah_4_nwmmge.jpg", 11, 8);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232237/National-Parks/Park-Photos/shenandoah_1_htdcwe.jpg", 11, 8);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232256/National-Parks/Park-Photos/saguro_2_ryfzzw.jpg", 11, 9);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232256/National-Parks/Park-Photos/saguro_3_vknqiz.jpg", 11, 9);
INSERT INTO `Photos` VALUES (null, "https://res.cloudinary.com/dcuwovsbv/image/upload/v1674232258/National-Parks/Park-Photos/saguro_1_lpkfwb.jpg", 11, 9);

INSERT INTO User_Favorites VALUES (null, 2, 8, 1);
INSERT INTO User_Favorites VALUES (null, 2, 7, 2);
INSERT INTO User_Favorites VALUES (null, 2, 5, 3);
INSERT INTO User_Favorites VALUES (null, 2, 4, 4);
INSERT INTO User_Favorites VALUES (null, 2, 2, 5);
INSERT INTO User_Favorites VALUES (null, 2, 3, 6);
INSERT INTO User_Favorites VALUES (null, 2, 1, 7);
INSERT INTO User_Favorites VALUES (null, 2, 6, 8);
INSERT INTO User_Favorites VALUES (null, 2, 9, 9);
INSERT INTO User_Favorites VALUES (null, 2, 4, 10);
INSERT INTO User_Favorites VALUES (null, 2, 4, 1);
INSERT INTO User_Favorites VALUES (null, 2, 5, 2);
INSERT INTO User_Favorites VALUES (null, 2, 8, 3);
INSERT INTO User_Favorites VALUES (null, 2, 7, 4);
INSERT INTO User_Favorites VALUES (null, 2, 9, 5);
INSERT INTO User_Favorites VALUES (null, 2, 2, 6);
INSERT INTO User_Favorites VALUES (null, 2, 6, 7);
INSERT INTO User_Favorites VALUES (null, 2, 1, 8);
INSERT INTO User_Favorites VALUES (null, 2, 3, 9);
INSERT INTO User_Favorites VALUES (null, 2, 2, 10);
INSERT INTO User_Favorites VALUES (null, 4, 8, 1);
INSERT INTO User_Favorites VALUES (null, 4, 7, 2);
INSERT INTO User_Favorites VALUES (null, 4, 5, 3);
INSERT INTO User_Favorites VALUES (null, 4, 4, 4);
INSERT INTO User_Favorites VALUES (null, 4, 2, 5);
INSERT INTO User_Favorites VALUES (null, 4, 3, 6);
INSERT INTO User_Favorites VALUES (null, 4, 1, 7);
INSERT INTO User_Favorites VALUES (null, 4, 6, 8);
INSERT INTO User_Favorites VALUES (null, 4, 9, 9);
INSERT INTO User_Favorites VALUES (null, 4, 4, 10);
INSERT INTO User_Favorites VALUES (null, 4, 4, 1);
INSERT INTO User_Favorites VALUES (null, 4, 5, 2);
INSERT INTO User_Favorites VALUES (null, 4, 8, 3);
INSERT INTO User_Favorites VALUES (null, 4, 7, 4);
INSERT INTO User_Favorites VALUES (null, 4, 9, 5);
INSERT INTO User_Favorites VALUES (null, 4, 2, 6);
INSERT INTO User_Favorites VALUES (null, 4, 6, 7);
INSERT INTO User_Favorites VALUES (null, 4, 1, 8);
INSERT INTO User_Favorites VALUES (null, 4, 3, 9);
INSERT INTO User_Favorites VALUES (null, 4, 2, 10);
INSERT INTO User_Favorites VALUES (null, 3, 8, 1);
INSERT INTO User_Favorites VALUES (null, 3, 7, 2);
INSERT INTO User_Favorites VALUES (null, 3, 5, 3);
INSERT INTO User_Favorites VALUES (null, 3, 4, 4);
INSERT INTO User_Favorites VALUES (null, 3, 2, 5);
INSERT INTO User_Favorites VALUES (null, 3, 3, 6);
INSERT INTO User_Favorites VALUES (null, 3, 1, 7);
INSERT INTO User_Favorites VALUES (null, 3, 6, 8);
INSERT INTO User_Favorites VALUES (null, 3, 9, 9);
INSERT INTO User_Favorites VALUES (null, 3, 4, 10);
INSERT INTO User_Favorites VALUES (null, 3, 4, 1);
INSERT INTO User_Favorites VALUES (null, 3, 5, 2);
INSERT INTO User_Favorites VALUES (null, 3, 8, 3);
INSERT INTO User_Favorites VALUES (null, 3, 7, 4);
INSERT INTO User_Favorites VALUES (null, 3, 9, 5);
INSERT INTO User_Favorites VALUES (null, 3, 2, 6);
INSERT INTO User_Favorites VALUES (null, 3, 6, 7);
INSERT INTO User_Favorites VALUES (null, 3, 1, 8);
INSERT INTO User_Favorites VALUES (null, 3, 3, 9);
INSERT INTO User_Favorites VALUES (null, 3, 2, 10);
INSERT INTO User_Favorites VALUES (null, 3, 1, 11);
INSERT INTO User_Favorites VALUES (null, 3, 3, 11);